### ISSUE TITLE
Plans for Melpa

### ISSUE THREAD

**Issue by arifer612** [fizban007/arxiv-mode#3]
Hi there, I've been using this package for weeks now and it works so beautifully with my workflow. I just want to know if you have plans to publish it onto Melpa since there may be others who could benefit greatly from it too!

**Comment by Simon-Lin** [comment]
Hi,
Sorry for the long wait. I'm proud to announce that arxiv-mode is now available on MELPA!
Be sure to check out the new features we added by downloading the newest version through MELPA.
