### ISSUE TITLE
[REQUEST] To list the Linked citations/references of a particular paper

### ISSUE THREAD

**Issue by choasma** [fizban007/arxiv-mode#4]
Hi All, 

Really appreciate this work that simplify the way I search the arxiv paper. Here is a feature request and wondering if there's a chance I can get a list of papers which cite the given paper. This feature is called Bibliographic Explorer on ArXiv platform, screenshoted below. Thanks

![image](https://user-images.githubusercontent.com/8385806/214956221-069c8590-9b59-4377-a10a-40196b377bec.png)

**Comment by Simon-Lin** [comment]
Hi,
I believe this is not possible as the arXiv API does not provide these information. For cross-referencing on Emacs I would recommend biblio.el (https://github.com/cpitclaudel/biblio.el) instead. It is an excellent package for fetching and searching for bibliographic information.

**Comment by choasma** [comment]
Cool Simon, Thanks for the suggestion and I'll both use arxiv-mode and biblio! Cheers
