### ISSUE TITLE
[feature request] Sorted search

### ISSUE THREAD

**Issue by hammerfunctor** [fizban007/arxiv-mode#5]
Sort by relevance, submission date or update date. See https://info.arxiv.org/help/api/user-manual.html#3113-sort-order-for-return-results

**Comment by ltmsyvag** [comment]
I second this feature request. For example, when I use `arxiv-read-author`, I expect to see the publications of a certain author from new to old. This sorting is very reasonable,  very needed, but seems missing for now.

**Comment by Simon-Lin** [comment]
Sorry for the late reply. Indeed I agree this is a nice feature request. There are also other features I have in mind (for example, showing the new articles by main category and cross-listing, etc). I have some free times during the new year break and I'll see what I can do!

**Comment by Simon-Lin** [comment]
Feature implemented (cb94571). Accessible via the refine-search menu or via arxiv-complex-search directly.
