### ISSUE TITLE
arxiv-search stopped working

### ISSUE THREAD

**Issue by arael** [fizban007/arxiv-mode#6]
I am using Emacs 29.1 on GNU/Linux and arxiv-search stopped working.

When I run arxiv-search with any pattern all I get is: No articles matching the search condition.

This happens with any kind of pattern.

Please let me know what other information to provide.

**Comment by Simon-Lin** [comment]
Did you mean that you are able to get the results via axriv-read-new and arxiv-read-recent and only arxiv-search failed?

**Comment by arael** [comment]
Sorry for wasting your time. I think that it was a temporary arxiv problem. Everything works fine again today.

**Comment by arael** [comment]
I tried again today. I was able to get the results one time. Then it stopped working again.

If I use arxiv-read-new function I get the message: Could not find any new submissions..Read from previous day instead? (y/n).

This holds true for any of the research fields that I select.

The arxiv-search function is back at showing the same message for any kind of search pattern: No articles matching the search condition.

**Comment by Simon-Lin** [comment]
It is a problem the API of arxiv.org and not of arxiv-mode. At the time of writing this reply I cannot access the API either.
You can check this via accessing the folloing link using your browser: 
[http://export.arxiv.org/api/query?search_query=all:electron](http://export.arxiv.org/api/query?search_query=all:electron)
If it fails to load then it means that this is an arxiv.org side issue.

**Comment by Simon-Lin** [comment]
API seems to be working now. Again this issue is not something we can control. One other thing along this line is that although the daily new submissions are said to be updated at 8pm EST each day, the actual update time is usually later and can take up to 2-3 hours.

**Comment by arael** [comment]
I see. Thank you for the explanations and for considering my report. I guess I can close this issue then.
